package com.tylerh.compressedores.Util;


import com.tylerh.compressedores.Init.BlockList;
import net.minecraft.world.level.block.Block;

public class ModInfo
{
    public static final String MOD_ID = "compressedores";
    public static final boolean GUI_DEFAULT = true;

    public static final String[] matCosts = {"9","81","729","6,561","59,049","531,441","4,782,969","43,046,721"};
    public static final String[] appendNames = {"Amethyst","Gold","Iron","Diamond","Emerald","Lapis","Quartz","Redstone","Coal","Clay"};
    public static final String[] extraNames = {"Andesite","Basalt","Blackstone","Calcite","Cobblestone","Cobbled Deepslate","Diorite","Dirt","Granite","Gravel","Netherrack","Sand","Tuff"};
    public static final Block[] amethystBlocks = {BlockList.blockAmethystCompressed.get(),BlockList.blockAmethystDouble.get(),BlockList.blockAmethystTriple.get(),BlockList.blockAmethystQuadruple.get(),BlockList.blockAmethystQuintuple.get(),BlockList.blockAmethystSextuple.get(),BlockList.blockAmethystSeptuple.get(),BlockList.blockAmethystOctuple.get()};
    public static final Block[] andesiteBlocks = {BlockList.blockAndesiteCompressed.get(),BlockList.blockAndesiteDouble.get(),BlockList.blockAndesiteTriple.get(),BlockList.blockAndesiteQuadruple.get(),BlockList.blockAndesiteQuintuple.get(),BlockList.blockAndesiteSextuple.get(),BlockList.blockAndesiteSeptuple.get(),BlockList.blockAndesiteOctuple.get()};
    public static final Block[] basaltBlocks = {BlockList.blockBasaltCompressed.get(),BlockList.blockBasaltDouble.get(),BlockList.blockBasaltTriple.get(),BlockList.blockBasaltQuadruple.get(),BlockList.blockBasaltQuintuple.get(),BlockList.blockBasaltSextuple.get(),BlockList.blockBasaltSeptuple.get(),BlockList.blockBasaltOctuple.get()};
    public static final Block[] blackstoneBlocks = {BlockList.blockBlackstoneCompressed.get(),BlockList.blockBlackstoneDouble.get(),BlockList.blockBlackstoneTriple.get(),BlockList.blockBlackstoneQuadruple.get(),BlockList.blockBlackstoneQuintuple.get(),BlockList.blockBlackstoneSextuple.get(),BlockList.blockBlackstoneSeptuple.get(),BlockList.blockBlackstoneOctuple.get()};
    public static final Block[] calciteBlocks = {BlockList.blockCalciteCompressed.get(),BlockList.blockCalciteDouble.get(),BlockList.blockCalciteTriple.get(),BlockList.blockCalciteQuadruple.get(),BlockList.blockCalciteQuintuple.get(),BlockList.blockCalciteSextuple.get(),BlockList.blockCalciteSeptuple.get(),BlockList.blockCalciteOctuple.get()};
    public static final Block[] clayBlocks = {BlockList.blockClayCompressed.get(),BlockList.blockClayDouble.get(),BlockList.blockClayTriple.get(),BlockList.blockClayQuadruple.get(),BlockList.blockClayQuintuple.get(),BlockList.blockClaySextuple.get(),BlockList.blockClaySeptuple.get(),BlockList.blockClayOctuple.get()};
    public static final Block[] coalBlocks = {BlockList.blockCoalCompressed.get(),BlockList.blockCoalDouble.get(),BlockList.blockCoalTriple.get(),BlockList.blockCoalQuadruple.get(),BlockList.blockCoalQuintuple.get(),BlockList.blockCoalSextuple.get(),BlockList.blockCoalSeptuple.get(),BlockList.blockCoalOctuple.get()};
    public static final Block[] cobbleBlocks = {BlockList.blockCobbleCompressed.get(),BlockList.blockCobbleDouble.get(),BlockList.blockCobbleTriple.get(),BlockList.blockCobbleQuadruple.get(),BlockList.blockCobbleQuintuple.get(),BlockList.blockCobbleSextuple.get(),BlockList.blockCobbleSeptuple.get(),BlockList.blockCobbleOctuple.get()};
    public static final Block[] deepslateCobbleBlocks = {BlockList.blockDeepslateCobbleCompressed.get(),BlockList.blockDeepslateCobbleDouble.get(),BlockList.blockDeepslateCobbleTriple.get(),BlockList.blockDeepslateCobbleQuadruple.get(),BlockList.blockDeepslateCobbleQuintuple.get(),BlockList.blockDeepslateCobbleSextuple.get(),BlockList.blockDeepslateCobbleSeptuple.get(),BlockList.blockDeepslateCobbleOctuple.get()};
    public static final Block[] diamondBlocks = {BlockList.blockDiamondCompressed.get(),BlockList.blockDiamondDouble.get(),BlockList.blockDiamondTriple.get(),BlockList.blockDiamondQuadruple.get(),BlockList.blockDiamondQuintuple.get(),BlockList.blockDiamondSextuple.get(),BlockList.blockDiamondSeptuple.get(),BlockList.blockDiamondOctuple.get()};
    public static final Block[] dioriteBlocks = {BlockList.blockDioriteCompressed.get(),BlockList.blockDioriteDouble.get(),BlockList.blockDioriteTriple.get(),BlockList.blockDioriteQuadruple.get(),BlockList.blockDioriteQuintuple.get(),BlockList.blockDioriteSextuple.get(),BlockList.blockDioriteSeptuple.get(),BlockList.blockDioriteOctuple.get()};
    public static final Block[] dirtBlocks = {BlockList.blockDirtCompressed.get(),BlockList.blockDirtDouble.get(),BlockList.blockDirtTriple.get(),BlockList.blockDirtQuadruple.get(),BlockList.blockDirtQuintuple.get(),BlockList.blockDirtSextuple.get(),BlockList.blockDirtSeptuple.get(),BlockList.blockDirtOctuple.get()};
    public static final Block[] emeraldBlocks = {BlockList.blockEmeraldCompressed.get(),BlockList.blockEmeraldDouble.get(),BlockList.blockEmeraldTriple.get(),BlockList.blockEmeraldQuadruple.get(),BlockList.blockEmeraldQuintuple.get(),BlockList.blockEmeraldSextuple.get(),BlockList.blockEmeraldSeptuple.get(),BlockList.blockEmeraldOctuple.get()};
    public static final Block[] goldBlocks = {BlockList.blockGoldCompressed.get(),BlockList.blockGoldDouble.get(),BlockList.blockGoldTriple.get(),BlockList.blockGoldQuadruple.get(),BlockList.blockGoldQuintuple.get(),BlockList.blockGoldSextuple.get(),BlockList.blockGoldSeptuple.get(),BlockList.blockGoldOctuple.get()};
    public static final Block[] graniteBlocks = {BlockList.blockGraniteCompressed.get(),BlockList.blockGraniteDouble.get(),BlockList.blockGraniteTriple.get(),BlockList.blockGraniteQuadruple.get(),BlockList.blockGraniteQuintuple.get(),BlockList.blockGraniteSextuple.get(),BlockList.blockGraniteSeptuple.get(),BlockList.blockGraniteOctuple.get()};
    public static final Block[] gravelBlocks = {BlockList.blockGravelCompressed.get(),BlockList.blockGravelDouble.get(),BlockList.blockGravelTriple.get(),BlockList.blockGravelQuadruple.get(),BlockList.blockGravelQuintuple.get(),BlockList.blockGravelSextuple.get(),BlockList.blockGravelSeptuple.get(),BlockList.blockGravelOctuple.get()};
    public static final Block[] ironBlocks = {BlockList.blockIronCompressed.get(),BlockList.blockIronDouble.get(),BlockList.blockIronTriple.get(),BlockList.blockIronQuadruple.get(),BlockList.blockIronQuintuple.get(),BlockList.blockIronSextuple.get(),BlockList.blockIronSeptuple.get(),BlockList.blockIronOctuple.get()};
    public static final Block[] lapisBlocks = {BlockList.blockLapisCompressed.get(),BlockList.blockLapisDouble.get(),BlockList.blockLapisTriple.get(),BlockList.blockLapisQuadruple.get(),BlockList.blockLapisQuintuple.get(),BlockList.blockLapisSextuple.get(),BlockList.blockLapisSeptuple.get(),BlockList.blockLapisOctuple.get()};
    public static final Block[] netherrackBlocks = {BlockList.blockNetherrackCompressed.get(),BlockList.blockNetherrackDouble.get(),BlockList.blockNetherrackTriple.get(),BlockList.blockNetherrackQuadruple.get(),BlockList.blockNetherrackQuintuple.get(),BlockList.blockNetherrackSextuple.get(),BlockList.blockNetherrackSeptuple.get(),BlockList.blockNetherrackOctuple.get()};
    public static final Block[] quartzBlocks = {BlockList.blockQuartzCompressed.get(),BlockList.blockQuartzDouble.get(),BlockList.blockQuartzTriple.get(),BlockList.blockQuartzQuadruple.get(),BlockList.blockQuartzQuintuple.get(),BlockList.blockQuartzSextuple.get(),BlockList.blockQuartzSeptuple.get(),BlockList.blockQuartzOctuple.get()};
    public static final Block[] redstoneBlocks = {BlockList.blockRedstoneCompressed.get(),BlockList.blockRedstoneDouble.get(),BlockList.blockRedstoneTriple.get(),BlockList.blockRedstoneQuadruple.get(),BlockList.blockRedstoneQuintuple.get(),BlockList.blockRedstoneSextuple.get(),BlockList.blockRedstoneSeptuple.get(),BlockList.blockRedstoneOctuple.get()};
    public static final Block[] sandBlocks = {BlockList.blockSandCompressed.get(),BlockList.blockSandDouble.get(),BlockList.blockSandTriple.get(),BlockList.blockSandQuadruple.get(),BlockList.blockSandQuintuple.get(),BlockList.blockSandSextuple.get(),BlockList.blockSandSeptuple.get(),BlockList.blockSandOctuple.get()};
    public static final Block[] tuffBlocks = {BlockList.blockTuffCompressed.get(),BlockList.blockTuffDouble.get(),BlockList.blockTuffTriple.get(),BlockList.blockTuffQuadruple.get(),BlockList.blockTuffQuintuple.get(),BlockList.blockTuffSextuple.get(),BlockList.blockTuffSeptuple.get(),BlockList.blockTuffOctuple.get()};
    public static final String ADVANCEMENT_BACKGROUND = "minecraft:textures/gui/advancements/backgrounds/stone.png";
}
